import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'hi' | 'te' | 'pt' | 'zh' | 'ar';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
  flag: string;
  dir?: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', label: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', label: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', label: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', dir: 'ltr' },
  { code: 'pt', label: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', dir: 'ltr' },
  { code: 'zh', label: 'Chinese', nativeName: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ar', label: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', dir: 'rtl' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.upload_csv': 'Upload CSV',
    'nav.patients': 'Patients',
    'nav.reports': 'Reports',
    'nav.diet_plans': 'Diet Plans',
    'nav.reference_ranges': 'Reference Ranges',
    'nav.analyzer_mapping': 'Analyzer Mapping',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    'nav.lock': 'Lock Session',
    'nav.engine_active': 'Engine Active',
    'nav.try_sample': 'Try Sample Data',
    'nav.fast_track': 'Hackathon Demo Fast Track',

    // Common Actions
    'action.upload_csv': 'Upload CSV',
    'action.process_csv': 'Process CSV',
    'action.view_report': 'View Report',
    'action.download_pdf': 'Download PDF',
    'action.print_report': 'Print Report',
    'action.diet_plan': 'Patient Diet Plan',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.search': 'Search...',
    'action.filter': 'Filter',
    'action.back_to_reports': 'Back to Reports',
    'action.adjust': 'Adjust',
    'action.regenerate': 'Regenerate',
    'action.sign_in': 'Sign In to Portal',

    // Status Badges
    'status.normal': 'NORMAL',
    'status.abnormal': 'ABNORMAL',
    'status.critical': 'CRITICAL',
    'status.low': 'LOW',
    'status.high': 'HIGH',
    'status.critical_low': 'CRITICAL LOW',
    'status.critical_high': 'CRITICAL HIGH',
    'status.active': 'Active',

    // Dashboard
    'dash.title': 'Automate Pathology Report Generation',
    'dash.tagline': '"From Analyzer Data to Actionable Laboratory Reports"',
    'dash.description': 'Transform raw analyser CSV data into structured, reference-aware laboratory reports with automated age & sex range selection, unit normalization, and critical threshold detection.',
    'dash.total_reports': 'Total Reports',
    'dash.normal_results': 'Normal Results',
    'dash.abnormal_results': 'Abnormal Results',
    'dash.critical_results': 'Critical Results',
    'dash.patients_processed': 'Patients Processed',
    'dash.csv_processed': 'CSV Files Processed',
    'dash.trend_title': '30-Day Pathology Status Trend Distribution',
    'dash.trend_subtitle': 'Historical trajectory of Normal vs. Abnormal vs. Critical diagnostic results',
    'dash.recent_reports': 'Recent Laboratory Reports',
    'dash.critical_alerts': 'Immediate Action: Critical Value Alerts',
    'dash.diet_plans_btn': 'Patient Diet Plans',

    // Table Columns
    'col.patient_id': 'Patient ID',
    'col.patient_name': 'Patient Name',
    'col.age_sex': 'Age / Sex',
    'col.report_date': 'Report Date',
    'col.tests': 'Tests',
    'col.abnormal': 'Abnormal',
    'col.critical': 'Critical',
    'col.status': 'Status',
    'col.action': 'Action',
    'col.result': 'Result',
    'col.reference_range': 'Reference Range',
    'col.analyzer': 'Analyzer',

    // Diet Plans
    'diet.title': 'Patient Clinical Diet Plans',
    'diet.subtitle': 'Personalized medical nutrition protocols synthesized directly from laboratory analyser findings',
    'diet.badge': 'Pathology Evidence-Based',
    'diet.total_plans': 'Total Diet Plans',
    'diet.glycemic_plans': 'Glycemic Plans',
    'diet.cardio_plans': 'Cardio / Lipids',
    'diet.renal_plans': 'Renal Support',
    'diet.anemia_plans': 'Anemia Recovery',
    'diet.schedule_tab': '7-Day Meal Schedule',
    'diet.exercise_tab': 'Exercise & Movement Protocol',
    'diet.foods_tab': 'Foods to Include & Avoid',
    'diet.rationale_tab': 'Clinical Rationale & Lifestyle',
    'diet.notes_tab': 'Nutritionist Notes & Verification',
    'diet.therapeutic_foods': 'Therapeutic Foods to Prioritize',
    'diet.restricted_foods': 'Foods to Restrict / Strictly Avoid',
    'diet.weekly_active_target': 'Weekly Active Target',
    'diet.exercise_intensity': 'Prescribed Intensity',
    'diet.prescribed_exercises': 'Clinical Exercise Prescriptions',
    'diet.exercise_schedule': '7-Day Workout & Movement Schedule',
    'diet.safety_precautions': 'Clinical Safety Precautions',
    'diet.rest_recovery': 'Rest & Recovery Protocol',
    'diet.daily_calories': 'Daily Calories',
    'diet.fluid_hydration': 'Fluid Hydration',
    'diet.sodium_ceiling': 'Sodium Ceiling',
    'diet.macro_ratio': 'Carbs / Pro / Fat',
    'diet.breakfast': 'Breakfast',
    'diet.lunch': 'Lunch',
    'diet.dinner': 'Dinner',
    'diet.snacks': 'Snacks',
    'diet.bedtime': 'Bedtime Routine',

    // Upload
    'upload.title': 'Upload Analyzer Output',
    'upload.subtitle': 'Upload a pathology analyser CSV file to automatically generate patient reports.',
    'upload.drag_drop': 'Drag and drop your analyser CSV here, or browse your files',
    'upload.supported': 'Standard Pathology CSV format: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'CSV Preview & Validation',

    // Auth
    'auth.title': 'Clinical Laboratory Information System',
    'auth.welcome': 'Secure Medical Staff Portal',
    'auth.email': 'Staff Email Address',
    'auth.password': 'Password / Access PIN',
    'auth.facility': 'Clinical Facility',
    'auth.role': 'Designated Practitioner Role',
    'auth.submit': 'Authenticate & Enter Portal',
    'auth.keep_active': 'Keep session active',
    'auth.quick_profiles': 'Quick Demo Sign-In Profiles',

    // Languages
    'lang.select': 'Language',
    'lang.english': 'English',
    'lang.spanish': 'Spanish',
    'lang.french': 'French',
    'lang.german': 'German',
    'lang.hindi': 'Hindi',
    'lang.telugu': 'Telugu',
    'lang.portuguese': 'Portuguese',
    'lang.chinese': 'Chinese',
    'lang.arabic': 'Arabic',
  },

  es: {
    // Nav
    'nav.dashboard': 'Panel Principal',
    'nav.upload_csv': 'Cargar CSV',
    'nav.patients': 'Pacientes',
    'nav.reports': 'Informes',
    'nav.diet_plans': 'Planes de Dieta',
    'nav.reference_ranges': 'Rangos de Referencia',
    'nav.analyzer_mapping': 'Mapeo de Analizadores',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    'nav.lock': 'Bloquear Sesión',
    'nav.engine_active': 'Motor Activo',
    'nav.try_sample': 'Probar Datos de Muestra',
    'nav.fast_track': 'Demo Rápido de Hackathon',

    // Common Actions
    'action.upload_csv': 'Subir CSV',
    'action.process_csv': 'Procesar CSV',
    'action.view_report': 'Ver Informe',
    'action.download_pdf': 'Descargar PDF',
    'action.print_report': 'Imprimir Informe',
    'action.diet_plan': 'Plan de Dieta del Paciente',
    'action.save': 'Guardar',
    'action.cancel': 'Cancelar',
    'action.search': 'Buscar...',
    'action.filter': 'Filtrar',
    'action.back_to_reports': 'Volver a Informes',
    'action.adjust': 'Ajustar',
    'action.regenerate': 'Regenerar',
    'action.sign_in': 'Iniciar Sesión en el Portal',

    // Status Badges
    'status.normal': 'NORMAL',
    'status.abnormal': 'ANORMAL',
    'status.critical': 'CRÍTICO',
    'status.low': 'BAJO',
    'status.high': 'ALTO',
    'status.critical_low': 'CRÍTICO BAJO',
    'status.critical_high': 'CRÍTICO ALTO',
    'status.active': 'Activo',

    // Dashboard
    'dash.title': 'Automatización de Informes de Patología',
    'dash.tagline': '"De Datos del Analizador a Informes Clínicos Accionables"',
    'dash.description': 'Transforme datos CSV brutos del analizador en informes de laboratorio estructurados con rangos por edad y sexo, normalización de unidades y detección de umbrales críticos.',
    'dash.total_reports': 'Total Informes',
    'dash.normal_results': 'Resultados Normales',
    'dash.abnormal_results': 'Resultados Anormales',
    'dash.critical_results': 'Resultados Críticos',
    'dash.patients_processed': 'Pacientes Procesados',
    'dash.csv_processed': 'Archivos CSV Procesados',
    'dash.trend_title': 'Tendencia de Estados de Patología en 30 Días',
    'dash.trend_subtitle': 'Trayectoria histórica de resultados Normales vs. Anormales vs. Críticos',
    'dash.recent_reports': 'Informes de Laboratorio Recientes',
    'dash.critical_alerts': 'Acción Inmediata: Alertas de Valores Críticos',
    'dash.diet_plans_btn': 'Planes de Dieta',

    // Table Columns
    'col.patient_id': 'ID Paciente',
    'col.patient_name': 'Nombre Paciente',
    'col.age_sex': 'Edad / Sexo',
    'col.report_date': 'Fecha Informe',
    'col.tests': 'Pruebas',
    'col.abnormal': 'Anormal',
    'col.critical': 'Crítico',
    'col.status': 'Estado',
    'col.action': 'Acción',
    'col.result': 'Resultado',
    'col.reference_range': 'Rango Referencia',
    'col.analyzer': 'Analizador',

    // Diet Plans
    'diet.title': 'Planes de Dieta Clínica para Pacientes',
    'diet.subtitle': 'Protocolos de nutrición médica personalizados sintetizados directamente de hallazgos del analizador',
    'diet.badge': 'Basado en Evidencia Patológica',
    'diet.total_plans': 'Total Planes de Dieta',
    'diet.glycemic_plans': 'Planes Glucémicos',
    'diet.cardio_plans': 'Cardio / Lípidos',
    'diet.renal_plans': 'Soporte Renal',
    'diet.anemia_plans': 'Recuperación de Anemia',
    'diet.schedule_tab': 'Horario de Comidas de 7 Días',
    'diet.foods_tab': 'Alimentos a Incluir y Evitar',
    'diet.rationale_tab': 'Justificación Clínica y Estilo de Vida',
    'diet.notes_tab': 'Notas de Nutricionista y Verificación',
    'diet.therapeutic_foods': 'Alimentos Terapéuticos a Priorizar',
    'diet.restricted_foods': 'Alimentos a Restringir / Evitar Estrictamente',
    'diet.daily_calories': 'Calorías Diarias',
    'diet.fluid_hydration': 'Hidratación Líquida',
    'diet.sodium_ceiling': 'Límite de Sodio',
    'diet.macro_ratio': 'Carb / Prot / Grasas',
    'diet.breakfast': 'Desayuno',
    'diet.lunch': 'Almuerzo',
    'diet.dinner': 'Cena',
    'diet.snacks': 'Meriendas',
    'diet.bedtime': 'Rutina para Dormir',

    // Upload
    'upload.title': 'Cargar Salida del Analizador',
    'upload.subtitle': 'Suba un archivo CSV del analizador de patología para generar informes de pacientes automáticamente.',
    'upload.drag_drop': 'Arrastre y suelte su CSV aquí, o explore sus archivos',
    'upload.supported': 'Formato CSV estándar: ID Paciente, Nombre, Edad, Sexo, Prueba, Resultado, Unidad, Analizador, Fecha',
    'upload.preview': 'Vista Previa y Validación de CSV',

    // Auth
    'auth.title': 'Sistema de Información de Laboratorio Clínico',
    'auth.welcome': 'Portal Seguro de Personal Médico',
    'auth.email': 'Correo del Personal',
    'auth.password': 'Contraseña / PIN de Acceso',
    'auth.facility': 'Centro Clínico',
    'auth.role': 'Rol del Profesional',
    'auth.submit': 'Autenticar e Ingresar al Portal',
    'auth.keep_active': 'Mantener sesión activa',
    'auth.quick_profiles': 'Perfiles de Demostración Rápida',

    // Languages
    'lang.select': 'Idioma',
    'lang.english': 'Inglés',
    'lang.spanish': 'Español',
    'lang.french': 'Francés',
    'lang.german': 'Alemán',
    'lang.hindi': 'Hindi',
    'lang.telugu': 'Telugu',
    'lang.portuguese': 'Portugués',
    'lang.chinese': 'Chino',
    'lang.arabic': 'Árabe',
  },

  fr: {
    // Nav
    'nav.dashboard': 'Tableau de Bord',
    'nav.upload_csv': 'Téléverser CSV',
    'nav.patients': 'Patients',
    'nav.reports': 'Rapports',
    'nav.diet_plans': 'Plans de Régime',
    'nav.reference_ranges': 'Valeurs de Référence',
    'nav.analyzer_mapping': 'Mappage d’Analyseur',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    'nav.lock': 'Verrouiller Session',
    'nav.engine_active': 'Moteur Actif',
    'nav.try_sample': 'Données d’Échantillon',
    'nav.fast_track': 'Démo Rapide Hackathon',

    // Common Actions
    'action.upload_csv': 'Téléverser CSV',
    'action.process_csv': 'Traiter le CSV',
    'action.view_report': 'Voir le Rapport',
    'action.download_pdf': 'Télécharger PDF',
    'action.print_report': 'Imprimer le Rapport',
    'action.diet_plan': 'Régime Alimentaire',
    'action.save': 'Enregistrer',
    'action.cancel': 'Annuler',
    'action.search': 'Rechercher...',
    'action.filter': 'Filtrer',
    'action.back_to_reports': 'Retour aux Rapports',
    'action.adjust': 'Ajuster',
    'action.regenerate': 'Régénérer',
    'action.sign_in': 'Connexion au Portail',

    // Status Badges
    'status.normal': 'NORMAL',
    'status.abnormal': 'ANORMAL',
    'status.critical': 'CRITIQUE',
    'status.low': 'BAS',
    'status.high': 'ÉLEVÉ',
    'status.critical_low': 'CRITIQUE BAS',
    'status.critical_high': 'CRITIQUE ÉLEVÉ',
    'status.active': 'Actif',

    // Dashboard
    'dash.title': 'Génération Automatisée de Rapports de Pathologie',
    'dash.tagline': '"Des Données d’Analyseurs aux Rapports de Laboratoire"',
    'dash.description': 'Transformez les fichiers CSV bruts en comptes rendus de laboratoire structurés avec intervalles d’âge et de sexe, normalisation et détection des seuils critiques.',
    'dash.total_reports': 'Total Rapports',
    'dash.normal_results': 'Résultats Normaux',
    'dash.abnormal_results': 'Résultats Anormaux',
    'dash.critical_results': 'Résultats Critiques',
    'dash.patients_processed': 'Patients Traités',
    'dash.csv_processed': 'Fichiers CSV Traités',
    'dash.trend_title': 'Tendance des Statuts sur 30 Jours',
    'dash.trend_subtitle': 'Évolution historique des résultats Normaux, Anormaux et Critiques',
    'dash.recent_reports': 'Rapports Récents',
    'dash.critical_alerts': 'Action Immédiate : Alertes de Valeurs Critiques',
    'dash.diet_plans_btn': 'Plans Alimentaires',

    // Table Columns
    'col.patient_id': 'ID Patient',
    'col.patient_name': 'Nom du Patient',
    'col.age_sex': 'Âge / Sexe',
    'col.report_date': 'Date du Rapport',
    'col.tests': 'Analyses',
    'col.abnormal': 'Anormal',
    'col.critical': 'Critique',
    'col.status': 'Statut',
    'col.action': 'Action',
    'col.result': 'Résultat',
    'col.reference_range': 'Intervalle Référence',
    'col.analyzer': 'Analyseur',

    // Diet Plans
    'diet.title': 'Régimes Cliniques Personnalisés',
    'diet.subtitle': 'Protocoles nutritionnels personnalisés synthétisés à partir des données de pathologie',
    'diet.badge': 'Fondé sur les Résultats de Laboratoire',
    'diet.total_plans': 'Total Plans Diététiques',
    'diet.glycemic_plans': 'Plans Glycémiques',
    'diet.cardio_plans': 'Cardio / Lipides',
    'diet.renal_plans': 'Support Rénal',
    'diet.anemia_plans': 'Anémie & Fer',
    'diet.schedule_tab': 'Planning 7 Jours',
    'diet.foods_tab': 'Aliments Conseillés & Déconseillés',
    'diet.rationale_tab': 'Justification Médicale',
    'diet.notes_tab': 'Observations & Signature',
    'diet.therapeutic_foods': 'Aliments Thérapeutiques à Privilégier',
    'diet.restricted_foods': 'Aliments à Restreindre / Éviter',
    'diet.daily_calories': 'Calories Journalières',
    'diet.fluid_hydration': 'Hydratation Quotidienne',
    'diet.sodium_ceiling': 'Plafond Sodium',
    'diet.macro_ratio': 'Glucides / Protéines / Lipides',
    'diet.breakfast': 'Petit Déjeuner',
    'diet.lunch': 'Déjeuner',
    'diet.dinner': 'Dîner',
    'diet.snacks': 'Collations',
    'diet.bedtime': 'Soirée / Coucher',

    // Upload
    'upload.title': 'Téléverser Données de l’Analyseur',
    'upload.subtitle': 'Déposez un fichier CSV pour éditer automatiquement les rapports de pathologie.',
    'upload.drag_drop': 'Glissez-déposez le fichier CSV ici ou parcourez vos dossiers',
    'upload.supported': 'Colonnes attendues : Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'Aperçu & Validation du CSV',

    // Auth
    'auth.title': 'Système d’Information de Laboratoire Médical',
    'auth.welcome': 'Portail Sécurisé du Personnel Médical',
    'auth.email': 'Adresse E-mail Professionnelle',
    'auth.password': 'Mot de Passe / Code PIN',
    'auth.facility': 'Établissement de Santé',
    'auth.role': 'Fonction Médicale',
    'auth.submit': 'Authentification et Entrée',
    'auth.keep_active': 'Maintenir la session active',
    'auth.quick_profiles': 'Comptes de Démonstration',

    // Languages
    'lang.select': 'Langue',
    'lang.english': 'Anglais',
    'lang.spanish': 'Espagnol',
    'lang.french': 'Français',
    'lang.german': 'Allemand',
    'lang.hindi': 'Hindi',
    'lang.telugu': 'Télougou',
    'lang.portuguese': 'Portugais',
    'lang.chinese': 'Chinois',
    'lang.arabic': 'Arabe',
  },

  de: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.upload_csv': 'CSV Hochladen',
    'nav.patients': 'Patienten',
    'nav.reports': 'Befunde',
    'nav.diet_plans': 'Ernährungspläne',
    'nav.reference_ranges': 'Referenzbereiche',
    'nav.analyzer_mapping': 'Analysegeräte-Mapping',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'nav.lock': 'Sitzung Sperren',
    'nav.engine_active': 'Engine Aktiv',
    'nav.try_sample': 'Beispieldaten Laden',
    'nav.fast_track': 'Hackathon Schnellstart',

    // Common Actions
    'action.upload_csv': 'CSV Hochladen',
    'action.process_csv': 'CSV Verarbeiten',
    'action.view_report': 'Befund Anzeigen',
    'action.download_pdf': 'PDF Herunterladen',
    'action.print_report': 'Befund Drucken',
    'action.diet_plan': 'Patienten-Ernährungsplan',
    'action.save': 'Speichern',
    'action.cancel': 'Abbrechen',
    'action.search': 'Suchen...',
    'action.filter': 'Filtern',
    'action.back_to_reports': 'Zurück zu Befunden',
    'action.adjust': 'Anpassen',
    'action.regenerate': 'Neu Generieren',
    'action.sign_in': 'Im Portal Anmelden',

    // Status Badges
    'status.normal': 'NORMAL',
    'status.abnormal': 'ABWEICHEND',
    'status.critical': 'KRITISCH',
    'status.low': 'NIEDRIG',
    'status.high': 'ERHÖHT',
    'status.critical_low': 'KRITISCH NIEDRIG',
    'status.critical_high': 'KRITISCH HOCH',
    'status.active': 'Aktiv',

    // Dashboard
    'dash.title': 'Pathologie-Befundgenerierung Automatisieren',
    'dash.tagline': '"Von Analysedaten zu Handlungsorientierten Laborbefunden"',
    'dash.description': 'Transformieren Sie rohe Analysegeräte-CSV-Daten in strukturierte, alters- und geschlechtsspezifische Laborberichte mit automatischer Einheiten-Standardisierung und kritischer Alarmerkennung.',
    'dash.total_reports': 'Befunde Gesamt',
    'dash.normal_results': 'Normale Ergebnisse',
    'dash.abnormal_results': 'Abweichende Ergebnisse',
    'dash.critical_results': 'Kritische Werte',
    'dash.patients_processed': 'Patienten Verarbeitet',
    'dash.csv_processed': 'CSV-Dateien Verarbeitet',
    'dash.trend_title': '30-Tage Status-Verteilungstrend',
    'dash.trend_subtitle': 'Historische Verteilung von Normal-, Abweichungs- und Kritisch-Befunden',
    'dash.recent_reports': 'Aktuelle Laborberichte',
    'dash.critical_alerts': 'Sofortmaßnahme: Kritische Alarmwerte',
    'dash.diet_plans_btn': 'Ernährungspläne',

    // Table Columns
    'col.patient_id': 'Patienten-ID',
    'col.patient_name': 'Patientenname',
    'col.age_sex': 'Alter / Geschlecht',
    'col.report_date': 'Befunddatum',
    'col.tests': 'Tests',
    'col.abnormal': 'Abweichend',
    'col.critical': 'Kritisch',
    'col.status': 'Status',
    'col.action': 'Aktion',
    'col.result': 'Ergebnis',
    'col.reference_range': 'Referenzbereich',
    'col.analyzer': 'Analysegerät',

    // Diet Plans
    'diet.title': 'Klinische Patienten-Ernährungspläne',
    'diet.subtitle': 'Evidenzbasierte klinische Ernährungsempfehlungen direkt basierend auf pathologischen Messwerten',
    'diet.badge': 'Pathologisch Fundiert',
    'diet.total_plans': 'Aktive Pläne',
    'diet.glycemic_plans': 'Glukose / Diabetes',
    'diet.cardio_plans': 'Kardiovaskulär / Lipide',
    'diet.renal_plans': 'Nierenschutz',
    'diet.anemia_plans': 'Anämie / Eisen',
    'diet.schedule_tab': '7-Tage-Mahlzeitenplan',
    'diet.foods_tab': 'Empfohlene & Zu Meidende Lebensmittel',
    'diet.rationale_tab': 'Klinische Begründung & Lebensstil',
    'diet.notes_tab': 'Ernährungsberatung & Signatur',
    'diet.therapeutic_foods': 'Therapeutisch Bevorzugte Lebensmittel',
    'diet.restricted_foods': 'Streng Zu Meidende Lebensmittel',
    'diet.daily_calories': 'Tageskalorien',
    'diet.fluid_hydration': 'Flüssigkeitszufuhr',
    'diet.sodium_ceiling': 'Natriumobergrenze',
    'diet.macro_ratio': 'Kohlenhydrate / Protein / Fett',
    'diet.breakfast': 'Frühstück',
    'diet.lunch': 'Mittagessen',
    'diet.dinner': 'Abendessen',
    'diet.snacks': 'Zwischenmahlzeiten',
    'diet.bedtime': 'Schlafenszeit-Routine',

    // Upload
    'upload.title': 'Analysator-CSV Hochladen',
    'upload.subtitle': 'Laden Sie eine CSV-Datei hoch, um automatisch strukturierte Patientenberichte zu erstellen.',
    'upload.drag_drop': 'CSV-Datei hier ablegen oder durchsuchen',
    'upload.supported': 'Standard-Spalten: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'CSV Vorschau & Validierung',

    // Auth
    'auth.title': 'Klinisches Laborinformationssystem',
    'auth.welcome': 'Sicheres Fachpersonal-Portal',
    'auth.email': 'Dienstliche E-Mail-Adresse',
    'auth.password': 'Passwort / PIN',
    'auth.facility': 'Medizinische Einrichtung',
    'auth.role': 'Mitarbeiterrolle',
    'auth.submit': 'Authentifizieren und Starten',
    'auth.keep_active': 'Sitzung aktiv halten',
    'auth.quick_profiles': 'Schnellzugriff-Demo-Profile',

    // Languages
    'lang.select': 'Sprache',
    'lang.english': 'Englisch',
    'lang.spanish': 'Spanisch',
    'lang.french': 'Französisch',
    'lang.german': 'Deutsch',
    'lang.hindi': 'Hindi',
    'lang.telugu': 'Telugu',
    'lang.portuguese': 'Portugiesisch',
    'lang.chinese': 'Chinesisch',
    'lang.arabic': 'Arabisch',
  },

  hi: {
    // Nav
    'nav.dashboard': 'डैशबोर्ड',
    'nav.upload_csv': 'सीएसवी अपलोड',
    'nav.patients': 'मरीज (Patients)',
    'nav.reports': 'लैब रिपोर्ट्स',
    'nav.diet_plans': 'आहार योजना (Diet Plans)',
    'nav.reference_ranges': 'रेफरेंस रेंज',
    'nav.analyzer_mapping': 'एनालाइज़र मैपिंग',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'साइन आउट',
    'nav.lock': 'सत्र लॉक करें',
    'nav.engine_active': 'इंजन सक्रिय',
    'nav.try_sample': 'सैंपल डेटा आज़माएं',
    'nav.fast_track': 'हैकाथॉन डेमो फास्ट ट्रैक',

    // Common Actions
    'action.upload_csv': 'सीएसवी अपलोड करें',
    'action.process_csv': 'सीएसवी प्रोसेस करें',
    'action.view_report': 'रिपोर्ट देखें',
    'action.download_pdf': 'पीडीएफ डाउनलोड',
    'action.print_report': 'रिपोर्ट प्रिंट करें',
    'action.diet_plan': 'मरीज की डाइट योजना',
    'action.save': 'सहेजें',
    'action.cancel': 'रद्द करें',
    'action.search': 'खोजें...',
    'action.filter': 'फ़िल्टर',
    'action.back_to_reports': 'रिपोर्ट्स पर वापस जाएं',
    'action.adjust': 'बदलें',
    'action.regenerate': 'पुनर्निर्मित करें',
    'action.sign_in': 'पोर्टल में साइन इन करें',

    // Status Badges
    'status.normal': 'सामान्य (NORMAL)',
    'status.abnormal': 'असामान्य (ABNORMAL)',
    'status.critical': 'गंभीर (CRITICAL)',
    'status.low': 'कम (LOW)',
    'status.high': 'अधिक (HIGH)',
    'status.critical_low': 'अति-गंभीर कम',
    'status.critical_high': 'अति-गंभीर अधिक',
    'status.active': 'सक्रिय',

    // Dashboard
    'dash.title': 'पैथोलॉजी रिपोर्ट स्वचालन प्लेटफॉर्म',
    'dash.tagline': '"एनालाइज़र डेटा से सटीक नैदानिक रिपोर्ट तक"',
    'dash.description': 'पैथोलॉजी एनालाइज़र सीएसवी डेटा को उम्र और लिंग आधारित उचित संदर्भ सीमाओं, इकाई मानकीकरण और महत्वपूर्ण अलर्ट के साथ पेशेवर रिपोर्ट में बदलें।',
    'dash.total_reports': 'कुल रिपोर्ट्स',
    'dash.normal_results': 'सामान्य परिणाम',
    'dash.abnormal_results': 'असामान्य परिणाम',
    'dash.critical_results': 'गंभीर परिणाम',
    'dash.patients_processed': 'कुल मरीज',
    'dash.csv_processed': 'सीएसवी फाइलें',
    'dash.trend_title': '30-दिवसीय पैथोलॉजी स्थिति रुझान',
    'dash.trend_subtitle': 'सामान्य बनाम असामान्य बनाम गंभीर परिणामों का ऐतिहासिक चार्ट',
    'dash.recent_reports': 'हालिया लैब रिपोर्ट्स',
    'dash.critical_alerts': 'त्वरित कार्रवाई: गंभीर अलर्ट',
    'dash.diet_plans_btn': 'डाइट प्लान्स देखें',

    // Table Columns
    'col.patient_id': 'मरीज आईडी',
    'col.patient_name': 'मरीज का नाम',
    'col.age_sex': 'उम्र / लिंग',
    'col.report_date': 'रिपोर्ट तिथि',
    'col.tests': 'परीक्षण',
    'col.abnormal': 'असामान्य',
    'col.critical': 'गंभीर',
    'col.status': 'स्थिति',
    'col.action': 'कार्रवाई',
    'col.result': 'परिणाम',
    'col.reference_range': 'संदर्भ रेंज',
    'col.analyzer': 'एनालाइज़र',

    // Diet Plans
    'diet.title': 'मरीजों की नैदानिक डाइट योजनाएं',
    'diet.subtitle': 'लैब टेस्ट परिणामों पर आधारित अनुकूलित चिकित्सकीय पोषण प्रोटोकॉल',
    'diet.badge': 'पैथोलॉजी आधारित आहार',
    'diet.total_plans': 'कुल सक्रिय योजनाएं',
    'diet.glycemic_plans': 'ग्लाइसेमिक / डायबिटीज',
    'diet.cardio_plans': 'हृदय व लिपिड',
    'diet.renal_plans': 'किडनी सुरक्षा',
    'diet.anemia_plans': 'एनीमिया व आयरन',
    'diet.schedule_tab': '7-दिवसीय भोजन समय सारणी',
    'diet.foods_tab': 'खाने योग्य व वर्जित खाद्य पदार्थ',
    'diet.rationale_tab': 'नैदानिक तर्क व जीवनशैली',
    'diet.notes_tab': 'आहार विशेषज्ञ नोट्स',
    'diet.therapeutic_foods': 'लाभकारी खाद्य पदार्थ',
    'diet.restricted_foods': 'कड़ाई से वर्जित खाद्य पदार्थ',
    'diet.daily_calories': 'दैनिक कैलोरी',
    'diet.fluid_hydration': 'दैनिक जल सेवन',
    'diet.sodium_ceiling': 'सोडियम सीमा',
    'diet.macro_ratio': 'कार्बोहाइड्रेट / प्रोटीन / वसा',
    'diet.breakfast': 'नाश्ता',
    'diet.lunch': 'दोपहर का भोजन',
    'diet.dinner': 'रात का खाना',
    'diet.snacks': 'शाम का नाश्ता',
    'diet.bedtime': 'सोने से पहले',

    // Upload
    'upload.title': 'एनालाइज़र सीएसवी अपलोड करें',
    'upload.subtitle': 'मरीज रिपोर्ट स्वतः जनरेट करने के लिए पैथोलॉजी सीएसवी फाइल अपलोड करें।',
    'upload.drag_drop': 'सीएसवी फाइल यहाँ खींचें और छोड़ें या ब्राउज़ करें',
    'upload.supported': 'मानक प्रारूप: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'डेटा पूर्वावलोकन एवं सत्यापन',

    // Auth
    'auth.title': 'क्लिनिकल लैबोरेटरी इंफॉर्मेशन सिस्टम',
    'auth.welcome': 'चिकित्सा स्टाफ सुरक्षित पोर्टल',
    'auth.email': 'स्टाफ ईमेल पता',
    'auth.password': 'पासवर्ड / पिन कोड',
    'auth.facility': 'चिकित्सा केंद्र',
    'auth.role': 'चिकित्सक पद',
    'auth.submit': 'सत्यापन करें और प्रवेश करें',
    'auth.keep_active': 'सत्र सक्रिय रखें',
    'auth.quick_profiles': 'त्वरित डेमो प्रोफाइल',

    // Languages
    'lang.select': 'भाषा',
    'lang.english': 'अंग्रेज़ी (English)',
    'lang.spanish': 'स्पैनिश (Español)',
    'lang.french': 'फ़्रेंच (Français)',
    'lang.german': 'जर्मन (Deutsch)',
    'lang.hindi': 'हिन्दी',
    'lang.telugu': 'तेलुगु (Telugu)',
    'lang.portuguese': 'पुर्तगाली (Português)',
    'lang.chinese': 'चीनी (中文)',
    'lang.arabic': 'अरबी (العربية)',
  },

  te: {
    // Nav
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.upload_csv': 'CSV అప్‌లోడ్',
    'nav.patients': 'రోగులు (Patients)',
    'nav.reports': 'ల్యాబ్ రిపోర్టులు',
    'nav.diet_plans': 'డైట్ ప్లాన్స్ (Diet Plans)',
    'nav.reference_ranges': 'రిఫరెన్స్ పరిధులు',
    'nav.analyzer_mapping': 'ఎనలైజర్ మ్యాపింగ్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.logout': 'సైన్ అవుట్',
    'nav.lock': 'సెషన్ లాక్ చేయండి',
    'nav.engine_active': 'ఇంజిన్ సక్రియంగా ఉంది',
    'nav.try_sample': 'నమూనా డేటాను ప్రయత్నించండి',
    'nav.fast_track': 'డెమో ఫాస్ట్ ట్రాక్',

    // Common Actions
    'action.upload_csv': 'CSV అప్‌లోడ్ చేయండి',
    'action.process_csv': 'CSV ప్రాసెస్ చేయండి',
    'action.view_report': 'రిపోర్ట్ చూడండి',
    'action.download_pdf': 'PDF డౌన్‌లోడ్',
    'action.print_report': 'రిపోర్ట్ ప్రింట్ చేయండి',
    'action.diet_plan': 'రోగి ఆహార ప్రణాళిక',
    'action.save': 'సేవ్ చేయండి',
    'action.cancel': 'రద్దు చేయండి',
    'action.search': 'శోధించండి...',
    'action.filter': 'ఫిల్టర్',
    'action.back_to_reports': 'రిపోర్టులకు తిరిగి వెళ్ళండి',
    'action.adjust': 'సవరించండి',
    'action.regenerate': 'మళ్లీ రూపొందించండి',
    'action.sign_in': 'పోర్టల్‌లోకి సైన్ ఇన్ చేయండి',

    // Status Badges
    'status.normal': 'సాధారణం (NORMAL)',
    'status.abnormal': 'అసాధారణం (ABNORMAL)',
    'status.critical': 'తీవ్రమైన ప్రమాదం (CRITICAL)',
    'status.low': 'తక్కువ (LOW)',
    'status.high': 'ఎక్కువ (HIGH)',
    'status.critical_low': 'అతి తక్కువ (CRITICAL LOW)',
    'status.critical_high': 'అతి ఎక్కువ (CRITICAL HIGH)',
    'status.active': 'సక్రియం',

    // Dashboard
    'dash.title': 'పాథాలజీ రిపోర్ట్ ఆటోమేషన్ ప్లాట్‌ఫారమ్',
    'dash.tagline': '"ఎనలైజర్ డేటా నుండి స్పష్టమైన వైద్య నివేదికల వరకు"',
    'dash.description': 'ఆటోమేటెడ్ వయస్సు మరియు లింగ సూచన పరిధులు, యూనిట్ సాధారణీకరణ మరియు క్లిష్టమైన హెచ్చరిక గుర్తింపుతో ముడి విశ్లేషణ CSV డేటాను ఖచ్చితమైన ల్యాబ్ నివేదికలుగా మార్చండి.',
    'dash.total_reports': 'మొత్తం నివేదికలు',
    'dash.normal_results': 'సాధారణ ఫలితాలు',
    'dash.abnormal_results': 'అసాధారణ ఫలితాలు',
    'dash.critical_results': 'తీవ్రమైన ఫలితాలు',
    'dash.patients_processed': 'పరీక్షించిన రోగులు',
    'dash.csv_processed': 'ప్రాసెస్ చేసిన CSV ఫైళ్లు',
    'dash.trend_title': '30-రోజుల పాథాలజీ స్థితి పంపిణీ ట్రెండ్',
    'dash.trend_subtitle': 'సాధారణ vs అసాధారణ vs తీవ్రమైన ఫలితాల చారిత్రక పరిణామం',
    'dash.recent_reports': 'ఇటీవలి ల్యాబ్ నివేదికలు',
    'dash.critical_alerts': 'తక్షణ చర్య: తీవ్రమైన హెచ్చరికలు',
    'dash.diet_plans_btn': 'రోగి ఆహార ప్రణాళికలు',

    // Table Columns
    'col.patient_id': 'రోగి ఐడీ (Patient ID)',
    'col.patient_name': 'రోగి పేరు',
    'col.age_sex': 'వయస్సు / లింగం',
    'col.report_date': 'తేదీ',
    'col.tests': 'పరీక్షలు',
    'col.abnormal': 'అసాధారణం',
    'col.critical': 'తీవ్రమైనవి',
    'col.status': 'స్థితి',
    'col.action': 'చర్య',
    'col.result': 'ఫలితం',
    'col.reference_range': 'రిఫరెన్స్ పరిధి',
    'col.analyzer': 'ఎనలైజర్',

    // Diet Plans
    'diet.title': 'రోగుల క్లినికల్ డైట్ ప్రణాళికలు',
    'diet.subtitle': 'ల్యాబ్ పరీక్ష ఫలితాల ఆధారంగా రూపొందించిన వ్యక్తిగతీకరించిన వైద్య పోషకాహార సూచనలు',
    'diet.badge': 'పాథాలజీ ఆధారిత పోషణ',
    'diet.total_plans': 'మొత్తం డైట్ ప్రణాళికలు',
    'diet.glycemic_plans': 'గ్లైసెమిక్ / డయాబెటిస్',
    'diet.cardio_plans': 'గుండె & లిపిడ్స్',
    'diet.renal_plans': 'కిడ్నీ సంరక్షణ',
    'diet.anemia_plans': 'రక్తహీనత & ఐరన్',
    'diet.schedule_tab': '7-రోజుల భోజన ప్రణాళిక',
    'diet.exercise_tab': 'వ్యాయామం & శారీరక ప్రణాళిక (Exercise Protocol)',
    'diet.foods_tab': 'తీసుకోవాల్సిన & నివారించాల్సిన ఆహారాలు',
    'diet.rationale_tab': 'వైద్య కారణాలు & జీవనశైలి మార్పులు',
    'diet.notes_tab': 'న్యూట్రిషనిస్ట్ సూచనలు & ధృవీకరణ',
    'diet.therapeutic_foods': 'ప్రాధాన్యత ఇవ్వవలసిన ఆరోగ్యకరమైన ఆహారాలు',
    'diet.restricted_foods': 'పూర్తిగా నివారించవలసిన ఆహారాలు',
    'diet.weekly_active_target': 'వారంవారీ వ్యాయామ లక్ష్యం',
    'diet.exercise_intensity': 'సిఫార్సు చేయబడిన తీవ్రత',
    'diet.prescribed_exercises': 'పాథాలజీ ఆధారిత వ్యాయామ సూచనలు',
    'diet.exercise_schedule': '7-రోజుల వ్యాయామ షెడ్యూల్',
    'diet.safety_precautions': 'వైద్య భద్రతా జాగ్రత్తలు',
    'diet.rest_recovery': 'విశ్రాంతి & రికవరీ ప్రణాళిక',
    'diet.daily_calories': 'రోజువారీ కేలరీలు',
    'diet.fluid_hydration': 'నీటి పరిమాణం (హైడ్రేషన్)',
    'diet.sodium_ceiling': 'సోడియం పరిమితి',
    'diet.macro_ratio': 'పిండి పదార్థాలు / ప్రోటీన్ / కొవ్వు',
    'diet.breakfast': 'అల్పాహారం (టిఫిన్)',
    'diet.lunch': 'మధ్యాహ్న భోజనం',
    'diet.dinner': 'రాత్రి భోజనం',
    'diet.snacks': 'సాయంత్రం స్నాక్స్',
    'diet.bedtime': 'పడుకునే ముందు అలవాటు',

    // Upload
    'upload.title': 'ఎనలైజర్ CSV అప్‌లోడ్ చేయండి',
    'upload.subtitle': 'రోగి ల్యాబ్ రిపోర్టులను స్వయంచాలకంగా రూపొందించడానికి పాథాలజీ CSV ఫైల్‌ను అప్‌లోడ్ చేయండి.',
    'upload.drag_drop': 'ఇక్కడ CSV ఫైల్‌ను లాగండి లేదా ఫైల్స్ ఎంచుకోండి',
    'upload.supported': 'ప్రామాణిక ఆకృతి: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'CSV ప్రివ్యూ & ధృవీకరణ',

    // Auth
    'auth.title': 'క్లినికల్ లాబొరేటరీ సమాచార వ్యవస్థ (LIS)',
    'auth.welcome': 'వైద్య సిబ్బంది సురక్షిత పోర్టల్',
    'auth.email': 'సిబ్బంది ఇమెయిల్ చిరునామా',
    'auth.password': 'పాస్‌వర్డ్ / యాక్సెస్ పిన్',
    'auth.facility': 'వైద్య కేంద్రం / హాస్పిటల్',
    'auth.role': 'వైద్య నిపుణుడి పాత్ర',
    'auth.submit': 'ధృవీకరించి పోర్టల్‌లోకి ప్రవేశించండి',
    'auth.keep_active': 'సెషన్ యాక్టివ్‌గా ఉంచండి',
    'auth.quick_profiles': 'త్వరిత డెమో సైన్-ఇన్ ప్రొఫైల్స్',

    // Languages
    'lang.select': 'భాష',
    'lang.english': 'ఆంగ్లం (English)',
    'lang.spanish': 'స్పానిష్ (Español)',
    'lang.french': 'ఫ్రెంచ్ (Français)',
    'lang.german': 'జర్మన్ (Deutsch)',
    'lang.hindi': 'హిందీ (हिन्दी)',
    'lang.telugu': 'తెలుగు (Telugu)',
    'lang.portuguese': 'పోర్చుగీస్ (Português)',
    'lang.chinese': 'చైనీస్ (中文)',
    'lang.arabic': 'అరబిక్ (العربية)',
  },

  pt: {
    // Nav
    'nav.dashboard': 'Painel',
    'nav.upload_csv': 'Carregar CSV',
    'nav.patients': 'Pacientes',
    'nav.reports': 'Laudos',
    'nav.diet_plans': 'Planos de Dieta',
    'nav.reference_ranges': 'Valores de Referência',
    'nav.analyzer_mapping': 'Mapeamento de Analisadores',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    'nav.lock': 'Bloquear Sessão',
    'nav.engine_active': 'Motor Ativo',
    'nav.try_sample': 'Carregar Amostra',
    'nav.fast_track': 'Demo Rápida Hackathon',

    // Common Actions
    'action.upload_csv': 'Enviar CSV',
    'action.process_csv': 'Processar CSV',
    'action.view_report': 'Ver Laudo',
    'action.download_pdf': 'Baixar PDF',
    'action.print_report': 'Imprimir Laudo',
    'action.diet_plan': 'Plano de Dieta do Paciente',
    'action.save': 'Salvar',
    'action.cancel': 'Cancelar',
    'action.search': 'Buscar...',
    'action.filter': 'Filtrar',
    'action.back_to_reports': 'Voltar aos Laudos',
    'action.adjust': 'Ajustar',
    'action.regenerate': 'Regenerar',
    'action.sign_in': 'Entrar no Portal',

    // Status Badges
    'status.normal': 'NORMAL',
    'status.abnormal': 'ALTERADO',
    'status.critical': 'CRÍTICO',
    'status.low': 'BAIXO',
    'status.high': 'ALTO',
    'status.critical_low': 'CRÍTICO BAIXO',
    'status.critical_high': 'CRÍTICO ALTO',
    'status.active': 'Ativo',

    // Dashboard
    'dash.title': 'Automação de Laudos Laboratoriais',
    'dash.tagline': '"Dos Dados do Analisador a Laudos Clínicos Acionáveis"',
    'dash.description': 'Transforme dados brutos CSV de analisadores em laudos estruturados com faixas de referência por idade e sexo, normalização de unidades e alertas críticos.',
    'dash.total_reports': 'Total de Laudos',
    'dash.normal_results': 'Resultados Normais',
    'dash.abnormal_results': 'Resultados Alterados',
    'dash.critical_results': 'Resultados Críticos',
    'dash.patients_processed': 'Pacientes Processados',
    'dash.csv_processed': 'Arquivos CSV',
    'dash.trend_title': 'Tendência de Status em 30 Dias',
    'dash.trend_subtitle': 'Distribuição histórica de resultados Normais, Alterados e Críticos',
    'dash.recent_reports': 'Laudos Recentes',
    'dash.critical_alerts': 'Ação Imediata: Alertas Críticos',
    'dash.diet_plans_btn': 'Planos Nutricionais',

    // Table Columns
    'col.patient_id': 'ID do Paciente',
    'col.patient_name': 'Nome do Paciente',
    'col.age_sex': 'Idade / Sexo',
    'col.report_date': 'Data do Laudo',
    'col.tests': 'Exames',
    'col.abnormal': 'Alterado',
    'col.critical': 'Crítico',
    'col.status': 'Status',
    'col.action': 'Ação',
    'col.result': 'Resultado',
    'col.reference_range': 'Intervalo de Referência',
    'col.analyzer': 'Analisador',

    // Diet Plans
    'diet.title': 'Planos Clínicos de Dieta',
    'diet.subtitle': 'Protocolos nutricionais personalizados baseados diretamente nos biomarcadores laboratoriais',
    'diet.badge': 'Baseado em Patologia',
    'diet.total_plans': 'Planos Ativos',
    'diet.glycemic_plans': 'Controle Glicêmico',
    'diet.cardio_plans': 'Cardiovascular / Lipídios',
    'diet.renal_plans': 'Proteção Renal',
    'diet.anemia_plans': 'Recuperação de Anemia',
    'diet.schedule_tab': 'Cardápio de 7 Dias',
    'diet.foods_tab': 'Alimentos Recomendados e Proibidos',
    'diet.rationale_tab': 'Justificativa Clínica e Estilo de Vida',
    'diet.notes_tab': 'Observações da Nutrição',
    'diet.therapeutic_foods': 'Alimentos Terapêuticos Prioritários',
    'diet.restricted_foods': 'Alimentos a Restringir / Evitar',
    'diet.daily_calories': 'Calorias Diárias',
    'diet.fluid_hydration': 'Hidratação Hídrica',
    'diet.sodium_ceiling': 'Limite de Sódio',
    'diet.macro_ratio': 'Carb / Prot / Gordura',
    'diet.breakfast': 'Café da Manhã',
    'diet.lunch': 'Almoço',
    'diet.dinner': 'Jantar',
    'diet.snacks': 'Lanches',
    'diet.bedtime': 'Ceia / Dormir',

    // Upload
    'upload.title': 'Carregar Saída do Analisador',
    'upload.subtitle': 'Envie um arquivo CSV para gerar relatórios de pacientes automaticamente.',
    'upload.drag_drop': 'Arraste e solte o CSV aqui, ou procure arquivos',
    'upload.supported': 'Colunas: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'Pré-visualização e Validação',

    // Auth
    'auth.title': 'Sistema de Informação Laboratorial',
    'auth.welcome': 'Portal Seguro da Equipe Médica',
    'auth.email': 'E-mail Corporativo',
    'auth.password': 'Senha / PIN de Acesso',
    'auth.facility': 'Unidade Laboratorial',
    'auth.role': 'Função Médica',
    'auth.submit': 'Autenticar e Acessar',
    'auth.keep_active': 'Manter sessão conectada',
    'auth.quick_profiles': 'Perfis de Demonstração Rápida',

    // Languages
    'lang.select': 'Idioma',
    'lang.english': 'Inglês',
    'lang.spanish': 'Espanhol',
    'lang.french': 'Francês',
    'lang.german': 'Alemão',
    'lang.hindi': 'Hindi',
    'lang.telugu': 'Télugo',
    'lang.portuguese': 'Português',
    'lang.chinese': 'Chinês',
    'lang.arabic': 'Árabe',
  },

  zh: {
    // Nav
    'nav.dashboard': '仪表板',
    'nav.upload_csv': '上传 CSV',
    'nav.patients': '患者列表',
    'nav.reports': '化验报告',
    'nav.diet_plans': '饮食方案',
    'nav.reference_ranges': '参考范围',
    'nav.analyzer_mapping': '仪器编码映射',
    'nav.settings': '系统设置',
    'nav.logout': '退出登录',
    'nav.lock': '锁定屏幕',
    'nav.engine_active': '分析引擎正常',
    'nav.try_sample': '加载演示数据',
    'nav.fast_track': '黑客松极速演示通道',

    // Common Actions
    'action.upload_csv': '上传 CSV 文件',
    'action.process_csv': '处理分析数据',
    'action.view_report': '查看报告',
    'action.download_pdf': '下载 PDF 报告',
    'action.print_report': '打印报告',
    'action.diet_plan': '患者临床饮食方案',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.search': '搜索...',
    'action.filter': '筛选',
    'action.back_to_reports': '返回报告列表',
    'action.adjust': '调整方案',
    'action.regenerate': '重新生成',
    'action.sign_in': '登录医疗系统',

    // Status Badges
    'status.normal': '正常',
    'status.abnormal': '异常',
    'status.critical': '危急',
    'status.low': '偏低',
    'status.high': '偏高',
    'status.critical_low': '危急低值',
    'status.critical_high': '危急高值',
    'status.active': '执行中',

    // Dashboard
    'dash.title': '病理检验报告自动化系统',
    'dash.tagline': '"从检验仪器原始数据到权威临床诊断报告"',
    'dash.description': '直接读取自动化分析仪原始 CSV 输出，智能匹配年龄和性别参考区间，自动进行单位标准化换算，并实施危急值即时预警。',
    'dash.total_reports': '报告总数',
    'dash.normal_results': '正常结果',
    'dash.abnormal_results': '异常结果',
    'dash.critical_results': '危急值结果',
    'dash.patients_processed': '已建档患者',
    'dash.csv_processed': '已处理 CSV 文件',
    'dash.trend_title': '近30天检验结果状态分布趋势',
    'dash.trend_subtitle': '正常、异常与危急报告历史变化轨迹',
    'dash.recent_reports': '最新检验报告',
    'dash.critical_alerts': '紧急处理：危急值预警',
    'dash.diet_plans_btn': '查看饮食方案',

    // Table Columns
    'col.patient_id': '患者编号',
    'col.patient_name': '患者姓名',
    'col.age_sex': '年龄 / 性别',
    'col.report_date': '检验日期',
    'col.tests': '检验项目',
    'col.abnormal': '异常数',
    'col.critical': '危急数',
    'col.status': '状态',
    'col.action': '操作',
    'col.result': '检验值',
    'col.reference_range': '临床参考区间',
    'col.analyzer': '检验仪器',

    // Diet Plans
    'diet.title': '患者临床定制饮食方案',
    'diet.subtitle': '依据病理化验指标异常直接推导的循证医学营养治疗方案',
    'diet.badge': '病理循证医学',
    'diet.total_plans': '方案总数',
    'diet.glycemic_plans': '血糖平衡方案',
    'diet.cardio_plans': '心血管与血脂方案',
    'diet.renal_plans': '肾脏保护方案',
    'diet.anemia_plans': '贫血与补铁方案',
    'diet.schedule_tab': '7天完整餐单安排',
    'diet.foods_tab': '宜食与禁忌食物清单',
    'diet.rationale_tab': '临床病理机制分析',
    'diet.notes_tab': '营养师医嘱与审核',
    'diet.therapeutic_foods': '优先推荐的食疗食物',
    'diet.restricted_foods': '严格限制或避免的食物',
    'diet.daily_calories': '每日建议热量',
    'diet.fluid_hydration': '建议每日饮水量',
    'diet.sodium_ceiling': '每日钠摄入上限',
    'diet.macro_ratio': '碳水 / 蛋白 / 脂肪比例',
    'diet.breakfast': '早餐',
    'diet.lunch': '午餐',
    'diet.dinner': '晚餐',
    'diet.snacks': '加餐 / 点心',
    'diet.bedtime': '睡前调理',

    // Upload
    'upload.title': '上传分析仪原始输出 CSV',
    'upload.subtitle': '上传病理分析仪生成的 CSV 文件，系统将自动清洗并生成规范化临床报告。',
    'upload.drag_drop': '将 CSV 文件拖放到此处，或点击浏览本地文件',
    'upload.supported': '标准表头格式：Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': '数据预览与验证报告',

    // Auth
    'auth.title': '临床病理实验室信息管理系统 (LIS)',
    'auth.welcome': '医务工作人员安全认证入口',
    'auth.email': '机构工作邮箱',
    'auth.password': '访问密码 / 凭证 PIN',
    'auth.facility': '所属医疗机构',
    'auth.role': '执业岗位角色',
    'auth.submit': '验证身份并进入系统',
    'auth.keep_active': '保持当前登录状态',
    'auth.quick_profiles': '演示账号一键登录',

    // Languages
    'lang.select': '语言',
    'lang.english': '英语 (English)',
    'lang.spanish': '西班牙语 (Español)',
    'lang.french': '法语 (Français)',
    'lang.german': '德语 (Deutsch)',
    'lang.hindi': '印地语 (हिन्दी)',
    'lang.telugu': '泰卢固语 (Telugu)',
    'lang.portuguese': '葡萄牙语 (Português)',
    'lang.chinese': '简体中文',
    'lang.arabic': '阿拉伯语 (العربية)',
  },

  ar: {
    // Nav
    'nav.dashboard': 'لوحة التحكم',
    'nav.upload_csv': 'تحميل ملف CSV',
    'nav.patients': 'المرضى',
    'nav.reports': 'التقارير المخبرية',
    'nav.diet_plans': 'الخطط الغذائية',
    'nav.reference_ranges': 'المعدلات الطبيعية',
    'nav.analyzer_mapping': 'توصيف أجهزة التحليل',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.lock': 'قفل الجلسة',
    'nav.engine_active': 'محرك التحليل نشط',
    'nav.try_sample': 'تحميل بيانات تجريبية',
    'nav.fast_track': 'عرض الهاكاثون السريع',

    // Common Actions
    'action.upload_csv': 'رفع CSV',
    'action.process_csv': 'معالجة البيانات',
    'action.view_report': 'عرض التقرير',
    'action.download_pdf': 'تحميل PDF',
    'action.print_report': 'طباعة التقرير',
    'action.diet_plan': 'خطة المريض الغذائية',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.search': 'بحث...',
    'action.filter': 'تصفية',
    'action.back_to_reports': 'العودة للتقارير',
    'action.adjust': 'تعديل',
    'action.regenerate': 'إعادة إنشاء',
    'action.sign_in': 'تسجيل الدخول للنظام',

    // Status Badges
    'status.normal': 'طبيعي',
    'status.abnormal': 'غير طبيعي',
    'status.critical': 'حرج للغاية',
    'status.low': 'منخفض',
    'status.high': 'مرتفع',
    'status.critical_low': 'حرج منخفض',
    'status.critical_high': 'حرج مرتفع',
    'status.active': 'نشط',

    // Dashboard
    'dash.title': 'أتمتة تقارير المختبر والباثولوجيا',
    'dash.tagline': '"من بيانات أجهزة التحليل إلى تقارير مخبرية دقيقة وقابلة للتنفيذ"',
    'dash.description': 'تحويل ملفات أجهزة التحليل المخبرية إلى تقارير معتمدة بناءً على العمر والجنس مع توحيد الوحدات والتنبيه التلقائي للقيم الحرجة.',
    'dash.total_reports': 'إجمالي التقارير',
    'dash.normal_results': 'نتائج طبيعية',
    'dash.abnormal_results': 'نتائج غير طبيعية',
    'dash.critical_results': 'نتائج حرجة',
    'dash.patients_processed': 'المرضى المسجلين',
    'dash.csv_processed': 'ملفات CSV المنجزة',
    'dash.trend_title': 'توزيع مسار النتائج المخبرية خلال 30 يومًا',
    'dash.trend_subtitle': 'المقارنة التاريخية بين النتائج الطبيعية، غير الطبيعية والحرجة',
    'dash.recent_reports': 'أحدث التقارير الطبية',
    'dash.critical_alerts': 'إجراء فوري: تنبيهات القيم الحرجة',
    'dash.diet_plans_btn': 'خطط التغذية العلاجية',

    // Table Columns
    'col.patient_id': 'رقم المريض',
    'col.patient_name': 'اسم المريض',
    'col.age_sex': 'العمر / الجنس',
    'col.report_date': 'تاريخ التقرير',
    'col.tests': 'الفحوصات',
    'col.abnormal': 'غير طبيعي',
    'col.critical': 'حرج',
    'col.status': 'الحالة',
    'col.action': 'إجراء',
    'col.result': 'النتيجة',
    'col.reference_range': 'المعدل المرجعي',
    'col.analyzer': 'جهاز التحليل',

    // Diet Plans
    'diet.title': 'الخطط الغذائية الطبية للمرضى',
    'diet.subtitle': 'بروتوكولات تغذية علاجية مصممة خصيصًا بناءً على نتائج التحاليل المخبرية',
    'diet.badge': 'مبني على الأدلة المخبرية',
    'diet.total_plans': 'إجمالي الخطط النشطة',
    'diet.glycemic_plans': 'تنظيم السكر في الدم',
    'diet.cardio_plans': 'صحة القلب والدهون',
    'diet.renal_plans': 'حماية وظائف الكلى',
    'diet.anemia_plans': 'علاج فقر الدم والحديد',
    'diet.schedule_tab': 'جدول الوجبات لـ 7 أيام',
    'diet.foods_tab': 'الأطعمة العلاجية والممنوعة',
    'diet.rationale_tab': 'التحليل الطبي ونمط الحياة',
    'diet.notes_tab': 'توصيات أخصائي التغذية',
    'diet.therapeutic_foods': 'أطعمة ينصح بها بشدة',
    'diet.restricted_foods': 'أطعمة يجب تجنبها أو الامتناع عنها',
    'diet.daily_calories': 'السعرات الحرارية اليومية',
    'diet.fluid_hydration': 'كمية السوائل والماء',
    'diet.sodium_ceiling': 'الحد الأقصى للصوديوم',
    'diet.macro_ratio': 'كربوهيدرات / بروتين / دهون',
    'diet.breakfast': 'الإفطار',
    'diet.lunch': 'الغداء',
    'diet.dinner': 'العشاء',
    'diet.snacks': 'وجبات خفيفة',
    'diet.bedtime': 'قبل النوم',

    // Upload
    'upload.title': 'رفع ملف أجهزة التحليل',
    'upload.subtitle': 'قم برفع ملف CSV لتوليد تقارير المرضى وحساب المعدلات الطبيعية تلقائيًا.',
    'upload.drag_drop': 'اسحب ملف CSV وأفلته هنا، أو تصفح جهازك',
    'upload.supported': 'الأعمدة المطلوبة: Patient ID, Name, Age, Sex, Test Name, Result, Unit, Analyzer, Date',
    'upload.preview': 'معاينة وتدقيق البيانات',

    // Auth
    'auth.title': 'نظام معلومات المختبرات الطبية (LIS)',
    'auth.welcome': 'بوابة الكادر الطبي المعتمدة',
    'auth.email': 'البريد الإلكتروني المهني',
    'auth.password': 'كلمة المرور / الرمز السري',
    'auth.facility': 'المنشأة الطبية',
    'auth.role': 'الدور الوظيفي',
    'auth.submit': 'تسجيل الدخول وتأكيد الهوية',
    'auth.keep_active': 'إبقاء الجلسة نشطة',
    'auth.quick_profiles': 'حسابات التجربة السريعة',

    // Languages
    'lang.select': 'اللغة',
    'lang.english': 'الإنجليزية (English)',
    'lang.spanish': 'الإسبانية (Español)',
    'lang.french': 'الفرنسية (Français)',
    'lang.german': 'الألمانية (Deutsch)',
    'lang.hindi': 'الهندية (हिन्दी)',
    'lang.telugu': 'التيلجو (Telugu)',
    'lang.portuguese': 'البرتغالية (Português)',
    'lang.chinese': 'الصينية (中文)',
    'lang.arabic': 'العربية',
  },
};

const PATIENT_PORTAL_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    'portal.title': 'MetroHealth Patient Portal',
    'portal.tagline': 'Personalized Laboratory Reports & Medical Wellness',
    'portal.patient_id': 'Verified Patient ID',
    'portal.doctor_portal': 'Doctor Portal',
    'portal.sign_out': 'Sign Out',
    'portal.active_profile': 'Active Patient Care Profile',
    'portal.welcome': 'Welcome,',
    'portal.primary_condition': 'Primary Diagnostic Condition:',
    'portal.attending_doctor': 'Attending Doctor:',
    'portal.latest_specimen': 'Latest Specimen:',
    'portal.download_report': 'Download Official Lab PDF',
    'portal.download_diet': 'Download Diet & Exercise PDF',
    'portal.daily_calories': 'Daily Calorie Target',
    'portal.metabolic_target': 'Metabolic Basal Target',
    'portal.hydration': 'Fluid Hydration',
    'portal.water_glasses': '8-10 glasses of water',
    'portal.exercise_goal': 'Weekly Exercise Goal',
    'portal.sodium_ceiling': 'Sodium Ceiling',
    'portal.dash_limit': 'DASH Heart-Safe Limit',
    'portal.tab_reports': 'My Diagnostic Lab Reports',
    'portal.tab_diet': 'My 7-Day Meal & Nutrition Plan',
    'portal.tab_exercise': 'My Exercise & Movement Protocol',
    'portal.tab_trends': 'Biomarker Health Trends',
    'portal.tab_profile': 'My Profile & Care Team',
    'portal.select_record': 'Select Diagnostic Record:',
    'portal.loading_records': 'Retrieving laboratory records...',
    'portal.no_reports': 'No diagnostic laboratory reports found for Patient ID:',
  },
  es: {
    'portal.title': 'Portal del Paciente MetroHealth',
    'portal.tagline': 'Informes de laboratorio y bienestar médico personalizados',
    'portal.patient_id': 'ID de paciente verificado',
    'portal.doctor_portal': 'Portal médico',
    'portal.sign_out': 'Cerrar sesión',
    'portal.active_profile': 'Perfil de atención activa',
    'portal.welcome': 'Bienvenido/a,',
    'portal.primary_condition': 'Afección diagnóstica principal:',
    'portal.attending_doctor': 'Médico responsable:',
    'portal.latest_specimen': 'Muestra más reciente:',
    'portal.download_report': 'Descargar informe oficial PDF',
    'portal.download_diet': 'Descargar PDF de dieta y ejercicio',
    'portal.daily_calories': 'Objetivo diario de calorías',
    'portal.metabolic_target': 'Objetivo metabólico basal',
    'portal.hydration': 'Hidratación',
    'portal.water_glasses': '8-10 vasos de agua',
    'portal.exercise_goal': 'Objetivo semanal de ejercicio',
    'portal.sodium_ceiling': 'Límite de sodio',
    'portal.dash_limit': 'Límite DASH saludable para el corazón',
    'portal.tab_reports': 'Mis informes de laboratorio',
    'portal.tab_diet': 'Mi plan de alimentación de 7 días',
    'portal.tab_exercise': 'Mi plan de ejercicio y movimiento',
    'portal.tab_trends': 'Tendencias de biomarcadores',
    'portal.tab_profile': 'Mi perfil y equipo médico',
    'portal.select_record': 'Seleccionar registro diagnóstico:',
    'portal.loading_records': 'Cargando registros de laboratorio...',
    'portal.no_reports': 'No se encontraron informes de laboratorio para el ID de paciente:',
  },
  fr: {
    'portal.title': 'Portail Patient MetroHealth',
    'portal.tagline': 'Rapports de laboratoire et bien-être médical personnalisés',
    'portal.patient_id': 'ID patient vérifié',
    'portal.doctor_portal': 'Portail médecin',
    'portal.sign_out': 'Déconnexion',
    'portal.active_profile': 'Profil de soins actif',
    'portal.welcome': 'Bienvenue,',
    'portal.primary_condition': 'Diagnostic principal :',
    'portal.attending_doctor': 'Médecin référent :',
    'portal.latest_specimen': 'Dernier prélèvement :',
    'portal.download_report': 'Télécharger le rapport officiel PDF',
    'portal.download_diet': 'Télécharger le PDF nutrition et exercice',
    'portal.daily_calories': 'Objectif calorique quotidien',
    'portal.metabolic_target': 'Objectif métabolique basal',
    'portal.hydration': 'Hydratation',
    'portal.water_glasses': '8-10 verres d’eau',
    'portal.exercise_goal': 'Objectif hebdomadaire d’exercice',
    'portal.sodium_ceiling': 'Limite de sodium',
    'portal.dash_limit': 'Limite DASH bénéfique pour le cœur',
    'portal.tab_reports': 'Mes rapports de laboratoire',
    'portal.tab_diet': 'Mon programme alimentaire sur 7 jours',
    'portal.tab_exercise': 'Mon programme d’exercice et de mouvement',
    'portal.tab_trends': 'Tendances des biomarqueurs',
    'portal.tab_profile': 'Mon profil et équipe soignante',
    'portal.select_record': 'Sélectionner un dossier diagnostique :',
    'portal.loading_records': 'Récupération des dossiers de laboratoire...',
    'portal.no_reports': 'Aucun rapport de laboratoire trouvé pour l’ID patient :',
  },
  de: {
    'portal.title': 'MetroHealth Patientenportal',
    'portal.tagline': 'Personalisierte Laborberichte und medizinisches Wohlbefinden',
    'portal.patient_id': 'Verifizierte Patienten-ID',
    'portal.doctor_portal': 'Arztportal',
    'portal.sign_out': 'Abmelden',
    'portal.active_profile': 'Aktives Patientenprofil',
    'portal.welcome': 'Willkommen,',
    'portal.primary_condition': 'Primäre Diagnose:',
    'portal.attending_doctor': 'Behandelnder Arzt:',
    'portal.latest_specimen': 'Neueste Probe:',
    'portal.download_report': 'Offiziellen Laborbericht als PDF herunterladen',
    'portal.download_diet': 'Ernährungs- und Trainingsplan als PDF herunterladen',
    'portal.daily_calories': 'Täglicher Kalorienbedarf',
    'portal.metabolic_target': 'Basaler Stoffwechselbedarf',
    'portal.hydration': 'Flüssigkeitszufuhr',
    'portal.water_glasses': '8-10 Gläser Wasser',
    'portal.exercise_goal': 'Wöchentliches Trainingsziel',
    'portal.sodium_ceiling': 'Natriumhöchstmenge',
    'portal.dash_limit': 'Herzgesunder DASH-Grenzwert',
    'portal.tab_reports': 'Meine Laborberichte',
    'portal.tab_diet': 'Mein 7-Tage-Ernährungsplan',
    'portal.tab_exercise': 'Mein Trainings- und Bewegungsplan',
    'portal.tab_trends': 'Biomarker-Trends',
    'portal.tab_profile': 'Mein Profil und Behandlungsteam',
    'portal.select_record': 'Diagnostischen Datensatz auswählen:',
    'portal.loading_records': 'Laborberichte werden abgerufen...',
    'portal.no_reports': 'Keine Laborberichte für die Patienten-ID gefunden:',
  },
  hi: {
    'portal.title': 'MetroHealth रोगी पोर्टल',
    'portal.tagline': 'व्यक्तिगत प्रयोगशाला रिपोर्ट और चिकित्सा स्वास्थ्य',
    'portal.patient_id': 'सत्यापित रोगी आईडी',
    'portal.doctor_portal': 'डॉक्टर पोर्टल',
    'portal.sign_out': 'साइन आउट',
    'portal.active_profile': 'सक्रिय रोगी देखभाल प्रोफ़ाइल',
    'portal.welcome': 'स्वागत है,',
    'portal.primary_condition': 'मुख्य निदान स्थिति:',
    'portal.attending_doctor': 'उपस्थित चिकित्सक:',
    'portal.latest_specimen': 'नवीनतम नमूना:',
    'portal.download_report': 'आधिकारिक लैब PDF डाउनलोड करें',
    'portal.download_diet': 'आहार और व्यायाम PDF डाउनलोड करें',
    'portal.daily_calories': 'दैनिक कैलोरी लक्ष्य',
    'portal.metabolic_target': 'बेसल चयापचय लक्ष्य',
    'portal.hydration': 'तरल जलयोजन',
    'portal.water_glasses': '8-10 गिलास पानी',
    'portal.exercise_goal': 'साप्ताहिक व्यायाम लक्ष्य',
    'portal.sodium_ceiling': 'सोडियम सीमा',
    'portal.dash_limit': 'हृदय-स्वस्थ DASH सीमा',
    'portal.tab_reports': 'मेरी लैब रिपोर्ट',
    'portal.tab_diet': 'मेरी 7-दिवसीय भोजन योजना',
    'portal.tab_exercise': 'मेरी व्यायाम और गतिविधि योजना',
    'portal.tab_trends': 'बायोमार्कर स्वास्थ्य रुझान',
    'portal.tab_profile': 'मेरी प्रोफ़ाइल और देखभाल टीम',
    'portal.select_record': 'नैदानिक रिकॉर्ड चुनें:',
    'portal.loading_records': 'प्रयोगशाला रिकॉर्ड प्राप्त किए जा रहे हैं...',
    'portal.no_reports': 'इस रोगी आईडी के लिए कोई लैब रिपोर्ट नहीं मिली:',
  },
  te: {
    'portal.title': 'MetroHealth రోగి పోర్టల్',
    'portal.tagline': 'వ్యక్తిగత ప్రయోగశాల నివేదికలు మరియు వైద్య ఆరోగ్యం',
    'portal.patient_id': 'ధృవీకరించిన రోగి ఐడి',
    'portal.doctor_portal': 'డాక్టర్ పోర్టల్',
    'portal.sign_out': 'సైన్ అవుట్',
    'portal.active_profile': 'క్రియాశీల రోగి సంరక్షణ ప్రొఫైల్',
    'portal.welcome': 'స్వాగతం,',
    'portal.primary_condition': 'ప్రధాన నిర్ధారణ పరిస్థితి:',
    'portal.attending_doctor': 'చికిత్స చేస్తున్న వైద్యుడు:',
    'portal.latest_specimen': 'తాజా నమూనా:',
    'portal.download_report': 'అధికారిక ల్యాబ్ PDF డౌన్‌లోడ్ చేయండి',
    'portal.download_diet': 'ఆహారం మరియు వ్యాయామ PDF డౌన్‌లోడ్ చేయండి',
    'portal.daily_calories': 'రోజువారీ కేలరీ లక్ష్యం',
    'portal.metabolic_target': 'ప్రాథమిక జీవక్రియ లక్ష్యం',
    'portal.hydration': 'ద్రవ జలసంరక్షణ',
    'portal.water_glasses': '8-10 గ్లాసుల నీరు',
    'portal.exercise_goal': 'వారపు వ్యాయామ లక్ష్యం',
    'portal.sodium_ceiling': 'సోడియం పరిమితి',
    'portal.dash_limit': 'గుండెకు సురక్షితమైన DASH పరిమితి',
    'portal.tab_reports': 'నా ల్యాబ్ నివేదికలు',
    'portal.tab_diet': 'నా 7-రోజుల ఆహార ప్రణాళిక',
    'portal.tab_exercise': 'నా వ్యాయామ మరియు కదలిక ప్రణాళిక',
    'portal.tab_trends': 'బయోమార్కర్ ఆరోగ్య ధోరణులు',
    'portal.tab_profile': 'నా ప్రొఫైల్ మరియు సంరక్షణ బృందం',
    'portal.select_record': 'నిర్ధారణ రికార్డును ఎంచుకోండి:',
    'portal.loading_records': 'ప్రయోగశాల రికార్డులను పొందుతోంది...',
    'portal.no_reports': 'ఈ రోగి ఐడికి ప్రయోగశాల నివేదికలు కనుగొనబడలేదు:',
  },
  pt: {
    'portal.title': 'Portal do Paciente MetroHealth',
    'portal.tagline': 'Relatórios laboratoriais e bem-estar médico personalizados',
    'portal.patient_id': 'ID de paciente verificado',
    'portal.doctor_portal': 'Portal médico',
    'portal.sign_out': 'Sair',
    'portal.active_profile': 'Perfil ativo de cuidados do paciente',
    'portal.welcome': 'Bem-vindo/a,',
    'portal.primary_condition': 'Condição diagnóstica principal:',
    'portal.attending_doctor': 'Médico responsável:',
    'portal.latest_specimen': 'Amostra mais recente:',
    'portal.download_report': 'Baixar PDF oficial do laboratório',
    'portal.download_diet': 'Baixar PDF de dieta e exercícios',
    'portal.daily_calories': 'Meta diária de calorias',
    'portal.metabolic_target': 'Meta metabólica basal',
    'portal.hydration': 'Hidratação',
    'portal.water_glasses': '8-10 copos de água',
    'portal.exercise_goal': 'Meta semanal de exercícios',
    'portal.sodium_ceiling': 'Limite de sódio',
    'portal.dash_limit': 'Limite DASH saudável para o coração',
    'portal.tab_reports': 'Meus relatórios laboratoriais',
    'portal.tab_diet': 'Meu plano alimentar de 7 dias',
    'portal.tab_exercise': 'Meu plano de exercícios e movimento',
    'portal.tab_trends': 'Tendências dos biomarcadores',
    'portal.tab_profile': 'Meu perfil e equipe de cuidados',
    'portal.select_record': 'Selecionar registro diagnóstico:',
    'portal.loading_records': 'Buscando registros laboratoriais...',
    'portal.no_reports': 'Nenhum relatório laboratorial encontrado para o ID do paciente:',
  },
  zh: {
    'portal.title': 'MetroHealth 患者门户',
    'portal.tagline': '个性化实验室报告与医疗健康服务',
    'portal.patient_id': '已验证患者编号',
    'portal.doctor_portal': '医生门户',
    'portal.sign_out': '退出登录',
    'portal.active_profile': '当前患者护理档案',
    'portal.welcome': '欢迎，',
    'portal.primary_condition': '主要诊断状况：',
    'portal.attending_doctor': '主治医生：',
    'portal.latest_specimen': '最新样本：',
    'portal.download_report': '下载官方实验室报告 PDF',
    'portal.download_diet': '下载饮食与运动 PDF',
    'portal.daily_calories': '每日热量目标',
    'portal.metabolic_target': '基础代谢目标',
    'portal.hydration': '每日饮水',
    'portal.water_glasses': '8-10 杯水',
    'portal.exercise_goal': '每周运动目标',
    'portal.sodium_ceiling': '钠摄入上限',
    'portal.dash_limit': 'DASH 护心上限',
    'portal.tab_reports': '我的实验室报告',
    'portal.tab_diet': '我的七日饮食计划',
    'portal.tab_exercise': '我的运动计划',
    'portal.tab_trends': '生物标志物健康趋势',
    'portal.tab_profile': '我的档案与护理团队',
    'portal.select_record': '选择诊断记录：',
    'portal.loading_records': '正在获取实验室记录...',
    'portal.no_reports': '未找到该患者编号的实验室报告：',
  },
  ar: {
    'portal.title': 'بوابة مرضى MetroHealth',
    'portal.tagline': 'تقارير مختبرية ورعاية صحية مخصصة',
    'portal.patient_id': 'رقم مريض موثّق',
    'portal.doctor_portal': 'بوابة الطبيب',
    'portal.sign_out': 'تسجيل الخروج',
    'portal.active_profile': 'ملف رعاية المريض النشط',
    'portal.welcome': 'مرحبًا،',
    'portal.primary_condition': 'الحالة التشخيصية الأساسية:',
    'portal.attending_doctor': 'الطبيب المعالج:',
    'portal.latest_specimen': 'أحدث عينة:',
    'portal.download_report': 'تنزيل تقرير المختبر الرسمي PDF',
    'portal.download_diet': 'تنزيل ملف النظام الغذائي والتمارين PDF',
    'portal.daily_calories': 'هدف السعرات اليومي',
    'portal.metabolic_target': 'هدف الأيض الأساسي',
    'portal.hydration': 'الترطيب بالسوائل',
    'portal.water_glasses': '8-10 أكواب من الماء',
    'portal.exercise_goal': 'هدف التمارين الأسبوعي',
    'portal.sodium_ceiling': 'الحد الأقصى للصوديوم',
    'portal.dash_limit': 'حد DASH الصحي للقلب',
    'portal.tab_reports': 'تقاريري المختبرية',
    'portal.tab_diet': 'خطتي الغذائية لمدة 7 أيام',
    'portal.tab_exercise': 'خطة التمارين والحركة',
    'portal.tab_trends': 'اتجاهات المؤشرات الحيوية',
    'portal.tab_profile': 'ملفي وفريق الرعاية',
    'portal.select_record': 'اختر السجل التشخيصي:',
    'portal.loading_records': 'جارٍ استرداد سجلات المختبر...',
    'portal.no_reports': 'لم يتم العثور على تقارير مختبرية لرقم المريض:',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currentLanguageOption: LanguageOption;
  t: (key: string, defaultText?: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const stored = localStorage.getItem('labreport_language') as LanguageCode;
      if (stored && SUPPORTED_LANGUAGES.some((l) => l.code === stored)) {
        return stored;
      }
    } catch (e) {
      // ignore
    }
    return 'en';
  });

  const currentLanguageOption =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  const isRtl = currentLanguageOption.dir === 'rtl';

  useEffect(() => {
    try {
      localStorage.setItem('labreport_language', language);
    } catch (e) {
      // ignore
    }
    document.documentElement.lang = language;
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
  }, [language, isRtl]);

  const setLanguage = (lang: LanguageCode) => {
    if (SUPPORTED_LANGUAGES.some((l) => l.code === lang)) {
      setLanguageState(lang);
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const patientPortalTranslation = PATIENT_PORTAL_TRANSLATIONS[language]?.[key];
    if (patientPortalTranslation) {
      return patientPortalTranslation;
    }
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    const enDict = TRANSLATIONS['en'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageOption,
        t,
        isRtl,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
